openapi: 3.0.1
info:
  title: GitHub Events Listener
  x-cortex-git: {}
  x-cortex-tag: github-events-listener
  x-cortex-type: aws-lambda
  x-cortex-infra:
    aws:
      cloudControl:
      - type: AWS::Lambda::Function
        region: us-east-2
        accountId: "136058102940"
        identifier: vista-lambda