openapi: 3.0.1
info:
  title: BE Engineering
  description: The backend engineering team.
  x-cortex-tag: be-engineering
  x-cortex-link:
  - url: https://www.atlassian.com/software/confluence
    name: Backend Eng Confluence Page
    type: DOCUMENTATION
  x-cortex-team:
    members:
    - name: Chase Lancaster
      role: null
      email: chase.lancaster@cortex.io
      description: null
      notificationsEnabled: true
    - name: Gianpaul Rachiele
      role: null
      email: gianpaul.rachiele@cortex.io
      description: null
      notificationsEnabled: true
    - name: Martin Stone
      role: null
      email: martin.stone@cortex.io
      description: null
      notificationsEnabled: true
    - name: Mike Guentzel
      role: null
      email: mike.guentzel@cortex.io
      description: null
      notificationsEnabled: true
    - name: Taylor Schmidt
      role: null
      email: taylor.schmidt@cortex.io
      description: null
      notificationsEnabled: true
    metadata:
      summary: Backend Engineering
      department: false
  x-cortex-type: team